// Record layouts from the SDIF v3 specification (United States Swimming, 28 April 1998).
// Each field: [start, length, key, label, type, codeTable, mandatory].
// start is 1-based, as in the specification. Types: CONST, CODE, ALPHA, NAME, DATE,
// TIME, INT, DEC, PHONE, USPS, USSNUM, LOGICAL. mandatory is 'M1', 'M2' or ''.
// Gaps between fields are the specification's "future use" space.

const ORG = [3, 1, 'org', 'Organization', 'CODE', 'ORG', 'M2'];
const TIMES = (base) => [
  [base, 8, 'seedTime', 'Seed time', 'TIME'],
  [base + 8, 1, 'seedCourse', 'Seed course', 'CODE', 'COURSE'],
  [base + 9, 8, 'prelimTime', 'Prelim time', 'TIME'],
  [base + 17, 1, 'prelimCourse', 'Prelim course', 'CODE', 'COURSE'],
  [base + 18, 8, 'swimOffTime', 'Swim-off time', 'TIME'],
  [base + 26, 1, 'swimOffCourse', 'Swim-off course', 'CODE', 'COURSE'],
  [base + 27, 8, 'finalsTime', 'Finals time', 'TIME'],
  [base + 35, 1, 'finalsCourse', 'Finals course', 'CODE', 'COURSE'],
  [base + 36, 2, 'prelimHeat', 'Prelim heat', 'INT'],
  [base + 38, 2, 'prelimLane', 'Prelim lane', 'INT'],
  [base + 40, 2, 'finalsHeat', 'Finals heat', 'INT'],
  [base + 42, 2, 'finalsLane', 'Finals lane', 'INT'],
  [base + 44, 3, 'prelimPlace', 'Prelim place', 'INT'],
  [base + 47, 3, 'finalsPlace', 'Finals place', 'INT'],
  [base + 50, 4, 'points', 'Points', 'DEC'],
  [base + 54, 2, 'timeClass', 'Event time class', 'CODE', 'TIME_CLASS'],
];

/** @type {Record<string, {name: string, fields: any[][]}>} */
export const RECORDS = {
  A0: {
    name: 'File description',
    fields: [
      ORG,
      [4, 8, 'sdifVersion', 'SDIF version', 'ALPHA'],
      [12, 2, 'fileCode', 'File type', 'CODE', 'FILE', 'M1'],
      [44, 20, 'software', 'Software', 'ALPHA'],
      [64, 10, 'softwareVersion', 'Software version', 'ALPHA'],
      [74, 20, 'contactName', 'Contact', 'ALPHA', null, 'M1'],
      [94, 12, 'contactPhone', 'Contact phone', 'PHONE', null, 'M1'],
      [106, 8, 'created', 'File created', 'DATE', null, 'M1'],
      [156, 2, 'submittedByLsc', 'Submitting LSC', 'ALPHA'],
    ],
  },
  B1: {
    name: 'Meet',
    fields: [
      ORG,
      [12, 30, 'name', 'Meet name', 'ALPHA', null, 'M1'],
      [42, 22, 'address1', 'Address 1', 'ALPHA'],
      [64, 22, 'address2', 'Address 2', 'ALPHA'],
      [86, 20, 'city', 'City', 'ALPHA', null, 'M2'],
      [106, 2, 'state', 'State', 'USPS', null, 'M2'],
      [108, 10, 'postalCode', 'Postal code', 'ALPHA'],
      [118, 3, 'country', 'Country', 'CODE', 'COUNTRY'],
      [121, 1, 'meetType', 'Meet type', 'CODE', 'MEET', 'M2'],
      [122, 8, 'start', 'Start date', 'DATE', null, 'M1'],
      [130, 8, 'end', 'End date', 'DATE', null, 'M2'],
      [138, 4, 'altitude', 'Pool altitude (ft)', 'INT'],
      [150, 1, 'course', 'Default course', 'CODE', 'COURSE'],
    ],
  },
  B2: {
    name: 'Meet host',
    fields: [
      ORG,
      [12, 30, 'name', 'Host name', 'ALPHA', null, 'M2'],
      [42, 22, 'address1', 'Address 1', 'ALPHA'],
      [64, 22, 'address2', 'Address 2', 'ALPHA'],
      [86, 20, 'city', 'City', 'ALPHA'],
      [106, 2, 'state', 'State', 'USPS'],
      [108, 10, 'postalCode', 'Postal code', 'ALPHA'],
      [118, 3, 'country', 'Country', 'CODE', 'COUNTRY'],
      [121, 12, 'phone', 'Host phone', 'PHONE'],
    ],
  },
  C1: {
    name: 'Team',
    fields: [
      ORG,
      [12, 6, 'teamCode', 'Team code', 'CODE', null, 'M1'],
      [18, 30, 'name', 'Team name', 'ALPHA', null, 'M1'],
      [48, 16, 'shortName', 'Short name', 'ALPHA'],
      [64, 22, 'address1', 'Address 1', 'ALPHA'],
      [86, 22, 'address2', 'Address 2', 'ALPHA'],
      [108, 20, 'city', 'City', 'ALPHA'],
      [128, 2, 'state', 'State', 'USPS'],
      [130, 10, 'postalCode', 'Postal code', 'ALPHA'],
      [140, 3, 'country', 'Country', 'CODE', 'COUNTRY'],
      [143, 1, 'region', 'Region', 'CODE', 'REGION'],
      [150, 1, 'teamCode5', 'Team code, 5th character', 'ALPHA'],
    ],
  },
  C2: {
    name: 'Team entry',
    fields: [
      ORG,
      [12, 6, 'teamCode', 'Team code', 'CODE', null, 'M2'],
      [18, 30, 'coach', 'Coach', 'ALPHA', null, 'M2'],
      [48, 12, 'coachPhone', 'Coach phone', 'PHONE'],
      [60, 6, 'entries', 'Individual entries', 'INT'],
      [66, 6, 'athletes', 'Athletes', 'INT'],
      [72, 5, 'relayEntries', 'Relay entries', 'INT'],
      [77, 6, 'relaySwimmers', 'Relay swimmer entries', 'INT'],
      [83, 6, 'splitRecords', 'Split records', 'INT'],
      [89, 16, 'displayName', 'Display name', 'ALPHA'],
      [150, 1, 'teamCode5', 'Team code, 5th character', 'ALPHA'],
    ],
  },
  D0: {
    name: 'Individual event',
    fields: [
      ORG,
      [12, 28, 'name', 'Swimmer', 'NAME', null, 'M1'],
      [40, 12, 'ussNumber', 'Registration number', 'ALPHA', null, 'M2'],
      [52, 1, 'attach', 'Attached', 'CODE', 'ATTACH'],
      [53, 3, 'citizen', 'Citizenship', 'CODE', 'CITIZEN'],
      [56, 8, 'birthDate', 'Birth date', 'DATE', null, 'M2'],
      [64, 2, 'ageClass', 'Age or class', 'ALPHA'],
      [66, 1, 'sex', 'Sex', 'CODE', 'SEX', 'M1'],
      [67, 1, 'eventSex', 'Event sex', 'CODE', 'EVENT_SEX', 'M1'],
      [68, 4, 'distance', 'Distance', 'INT', null, 'M1'],
      [72, 1, 'stroke', 'Stroke', 'CODE', 'STROKE', 'M1'],
      [73, 4, 'eventNumber', 'Event number', 'ALPHA'],
      [77, 4, 'eventAge', 'Event age group', 'CODE', 'EVENT_AGE', 'M1'],
      [81, 8, 'swimDate', 'Swim date', 'DATE', null, 'M2'],
      ...TIMES(89),
      [145, 1, 'flight', 'Flight', 'ALPHA'],
    ],
  },
  D1: {
    name: 'Individual administrative',
    fields: [
      ORG,
      [12, 6, 'teamCode', 'Team code', 'CODE'],
      [18, 1, 'teamCode5', 'Team code, 5th character', 'ALPHA'],
      [19, 28, 'name', 'Swimmer', 'NAME', null, 'M1'],
      [48, 12, 'ussNumber', 'Registration number', 'ALPHA', null, 'M2'],
      [60, 1, 'attach', 'Attached', 'CODE', 'ATTACH'],
      [61, 3, 'citizen', 'Citizenship', 'CODE', 'CITIZEN'],
      [64, 8, 'birthDate', 'Birth date', 'DATE', null, 'M2'],
      [72, 2, 'ageClass', 'Age or class', 'ALPHA'],
      [74, 1, 'sex', 'Sex', 'CODE', 'SEX', 'M1'],
      [75, 30, 'admin1', 'Admin info 1', 'ALPHA'],
      [105, 20, 'admin4', 'Admin info 4', 'ALPHA'],
      [125, 12, 'phone1', 'Phone 1', 'PHONE'],
      [137, 12, 'phone2', 'Phone 2', 'PHONE'],
      [149, 8, 'registered', 'Registration date', 'DATE'],
      [157, 1, 'member', 'Membership transaction', 'CODE', 'MEMBER'],
    ],
  },
  D2: {
    name: 'Individual contact',
    fields: [
      ORG,
      [12, 6, 'teamCode', 'Team code', 'CODE'],
      [18, 1, 'teamCode5', 'Team code, 5th character', 'ALPHA'],
      [19, 28, 'name', 'Swimmer', 'NAME', null, 'M1'],
      [47, 30, 'mailName', 'Mailing name', 'ALPHA'],
      [77, 30, 'street', 'Street', 'ALPHA'],
      [107, 20, 'city', 'City', 'ALPHA'],
      [127, 2, 'state', 'State', 'USPS'],
      [129, 12, 'countryName', 'Country (text)', 'ALPHA'],
      [141, 10, 'postalCode', 'Postal code', 'ALPHA'],
      [151, 3, 'country', 'Country', 'CODE', 'COUNTRY'],
      [154, 1, 'region', 'Region', 'CODE', 'REGION'],
      [155, 1, 'answer', 'Also a member (retired code)', 'ALPHA'],
      [156, 1, 'season', 'Season', 'CODE', 'SEASON'],
    ],
  },
  D3: {
    name: 'Individual information',
    fields: [
      [3, 14, 'ussNumberNew', 'Registration number (new)', 'USSNUM', null, 'M2'],
      [17, 15, 'preferredName', 'Preferred first name', 'ALPHA'],
      [32, 2, 'ethnicity', 'Ethnicity', 'CODE', 'ETHNICITY'],
      [34, 1, 'juniorHigh', 'Junior high school', 'LOGICAL'],
      [35, 1, 'seniorHigh', 'Senior high school', 'LOGICAL'],
      [36, 1, 'ymca', 'YMCA/YWCA', 'LOGICAL'],
      [37, 1, 'college', 'College', 'LOGICAL'],
      [38, 1, 'summerLeague', 'Summer league', 'LOGICAL'],
      [39, 1, 'masters', 'Masters', 'LOGICAL'],
      [40, 1, 'disabledSports', 'Disabled sports', 'LOGICAL'],
      [41, 1, 'waterPolo', 'Water polo', 'LOGICAL'],
      [42, 1, 'none', 'None of these', 'LOGICAL'],
    ],
  },
  E0: {
    name: 'Relay event',
    fields: [
      ORG,
      [12, 1, 'relayLetter', 'Relay letter', 'ALPHA', null, 'M1'],
      [13, 6, 'teamCode', 'Team code', 'CODE', null, 'M1'],
      [19, 2, 'legCount', 'F0 records following', 'INT'],
      [21, 1, 'eventSex', 'Event sex', 'CODE', 'EVENT_SEX', 'M1'],
      [22, 4, 'distance', 'Distance', 'INT', null, 'M1'],
      [26, 1, 'stroke', 'Stroke', 'CODE', 'STROKE', 'M1'],
      [27, 4, 'eventNumber', 'Event number', 'ALPHA'],
      [31, 4, 'eventAge', 'Event age group', 'CODE', 'EVENT_AGE', 'M1'],
      [35, 3, 'totalAge', 'Total age', 'INT'],
      [38, 8, 'swimDate', 'Swim date', 'DATE', null, 'M2'],
      ...TIMES(46),
    ],
  },
  F0: {
    name: 'Relay swimmer',
    fields: [
      ORG,
      [16, 6, 'teamCode', 'Team code', 'CODE', null, 'M1'],
      [22, 1, 'relayLetter', 'Relay letter', 'ALPHA', null, 'M1'],
      [23, 28, 'name', 'Swimmer', 'NAME', null, 'M1'],
      [51, 12, 'ussNumber', 'Registration number', 'ALPHA', null, 'M2'],
      [63, 3, 'citizen', 'Citizenship', 'CODE', 'CITIZEN'],
      [66, 8, 'birthDate', 'Birth date', 'DATE', null, 'M2'],
      [74, 2, 'ageClass', 'Age or class', 'ALPHA'],
      [76, 1, 'sex', 'Sex', 'CODE', 'SEX', 'M1'],
      [77, 1, 'prelimLeg', 'Prelim leg', 'CODE', 'ORDER', 'M1'],
      [78, 1, 'swimOffLeg', 'Swim-off leg', 'CODE', 'ORDER', 'M1'],
      [79, 1, 'finalsLeg', 'Finals leg', 'CODE', 'ORDER', 'M1'],
      [80, 8, 'legTime', 'Leg time', 'TIME'],
      [88, 1, 'legCourse', 'Leg course', 'CODE', 'COURSE'],
      [89, 4, 'takeOff', 'Take-off time (s)', 'DEC'],
      [93, 14, 'ussNumberNew', 'Registration number (new)', 'USSNUM', null, 'M2'],
      [107, 15, 'preferredName', 'Preferred first name', 'ALPHA'],
    ],
  },
  G0: {
    name: 'Splits',
    fields: [
      ORG,
      [16, 28, 'name', 'Swimmer', 'NAME'],
      [44, 12, 'ussNumber', 'Registration number', 'ALPHA'],
      [56, 1, 'sequence', 'Record sequence', 'INT', null, 'M1'],
      [57, 2, 'totalSplits', 'Total splits', 'INT', null, 'M1'],
      [59, 4, 'splitDistance', 'Split distance', 'INT', null, 'M1'],
      [63, 1, 'splitCode', 'Split type', 'CODE', 'SPLIT', 'M1'],
      ...Array.from({ length: 10 }, (_, i) => [64 + i * 8, 8, `split${i + 1}`, `Split ${i + 1}`, 'TIME']),
      [144, 1, 'round', 'Round', 'CODE', 'PRELIMS_FINALS'],
    ],
  },
  J0: {
    name: 'Meet qualifying times',
    fields: [
      [3, 8, 'effective', 'Effective date', 'DATE', null, 'M1'],
      [11, 1, 'meetType', 'Meet type', 'CODE', 'MEET', 'M1'],
      [17, 1, 'eventSex', 'Event sex', 'CODE', 'EVENT_SEX', 'M1'],
      [18, 4, 'distance', 'Distance', 'INT', null, 'M1'],
      [22, 1, 'stroke', 'Stroke', 'CODE', 'STROKE', 'M1'],
      [23, 8, 'scy', 'SCY time', 'TIME'],
      [31, 8, 'scm', 'SCM time', 'TIME'],
      [39, 8, 'lcm', 'LCM time', 'TIME'],
      [47, 4, 'eventAge', 'Event age group', 'CODE', 'EVENT_AGE', 'M1'],
      [51, 1, 'zone', 'Zone', 'CODE', 'ZONE'],
      [52, 2, 'region', 'Region', 'ALPHA'],
      [54, 2, 'lsc', 'LSC', 'CODE', 'LSC'],
    ],
  },
  J1: {
    name: 'National age group times',
    fields: [
      [3, 8, 'effective', 'Effective date', 'DATE', null, 'M1'],
      [11, 1, 'eventSex', 'Event sex', 'CODE', 'EVENT_SEX', 'M1'],
      [12, 4, 'distance', 'Distance', 'INT', null, 'M1'],
      [16, 1, 'stroke', 'Stroke', 'CODE', 'STROKE', 'M1'],
      [17, 4, 'eventAge', 'Event age group', 'CODE', 'EVENT_AGE', 'M1'],
      [21, 1, 'course', 'Course', 'CODE', 'COURSE', 'M1'],
      ...['BB', 'B', 'A', 'AA', 'AAA', 'AAAA'].map((s, i) => [22 + i * 8, 8, `std${s}`, `${s} time`, 'TIME']),
    ],
  },
  J2: {
    name: 'Motivational times',
    fields: [
      [3, 1, 'eventSex', 'Event sex', 'CODE', 'EVENT_SEX', 'M1'],
      [4, 4, 'distance', 'Distance', 'INT', null, 'M1'],
      [8, 1, 'stroke', 'Stroke', 'CODE', 'STROKE', 'M1'],
      [9, 4, 'color', 'Color', 'CODE', 'COLOR', 'M1'],
      [13, 8, 'scy1', 'SCY level 1', 'TIME'],
      [21, 8, 'scy2', 'SCY level 2', 'TIME'],
      [29, 8, 'scy3', 'SCY level 3', 'TIME'],
      [37, 8, 'lcm1', 'LCM level 1', 'TIME'],
      [45, 8, 'lcm2', 'LCM level 2', 'TIME'],
      [53, 8, 'lcm3', 'LCM level 3', 'TIME'],
      [61, 8, 'effective', 'Effective date', 'DATE', null, 'M1'],
    ],
  },
  Z0: {
    name: 'File terminator',
    fields: [
      ORG,
      [12, 2, 'fileCode', 'File type', 'CODE', 'FILE', 'M1'],
      [14, 30, 'notes', 'Notes', 'ALPHA'],
      [44, 3, 'bCount', 'B records', 'INT'],
      [47, 3, 'meetCount', 'Meets', 'INT'],
      [50, 4, 'cCount', 'C records', 'INT'],
      [54, 4, 'teamCount', 'Teams', 'INT'],
      [58, 6, 'dCount', 'D records', 'INT'],
      [64, 6, 'swimmerCount', 'Swimmers', 'INT'],
      [70, 5, 'eCount', 'E records', 'INT'],
      [75, 6, 'fCount', 'F records', 'INT'],
      [81, 6, 'gCount', 'G records', 'INT'],
      [87, 5, 'batch', 'Batch number', 'INT'],
      [92, 3, 'newMembers', 'New members', 'INT'],
      [95, 3, 'renewMembers', 'Renewed members', 'INT'],
      [98, 3, 'changedMembers', 'Changed members', 'INT'],
      [101, 3, 'deletedMembers', 'Deleted members', 'INT'],
    ],
  },
};

/** Data width of one record. The spec's 162 bytes include the closing CR LF. */
export const RECORD_LENGTH = 160;
